version: "3.8"
services:
    dcai:
        tty: true
        build:
            context: ./
            dockerfile: Dockerfile
        shm_size: "8gb"
        image: dcai
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: "all" # use all GPU devices on host machine
                          capabilities: [ gpu ]
        entrypoint: bash
        ports:
            - "8888:8888"
        volumes:
            - .:/dcai
